name: on push
on:
  push:
    branches:
      - master

env:
  CACHE_PATH: |
    **/node_modules
    ~/.cache/Cypress
    ~/.cache/yarn/v6
    ~/setup-pnpm/node_modules/.bin/store/v3
  FILES_TO_DELETE: |
    sudo rm -rf "/usr/share/dotnet"
    sudo rm -rf "/usr/share/swift"
    sudo rm -rf "/usr/local/share/boost"
    sudo rm -rf /opt/ghc
    sudo rm -rf "/usr/local/share/boost"
    sudo rm -rf "/usr/local/lib/android/sdk"
    sudo rm -rf "/opt/hostedtoolcache/Python"
    sudo rm -rf "/opt/hostedtoolcache/go"
    sudo rm -rf "/opt/hostedtoolcache/CodeQL"
    sudo rm -rf "/var/lib/gems"
    sudo rm -rf "$AGENT_TOOLSDIRECTORY"
    sudo apt-get clean -y
    sudo apt-get autoremove -y

jobs:

  # Stop previous runs
  stop-previous-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

  # Create cache for all samples
  cache:
    runs-on: ubuntu-22.04
    needs: stop-previous-run
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Free up some space
        run: ${{ env.FILES_TO_DELETE }}

      - name: Cache pnpm and Cypress
        uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: ${{ env.CACHE_PATH }}
          key: e2e-cache-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install deps
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile
